#spring:
#  application:
#    name: hhplus_concert
#  profiles:
#    active: local
#  springdoc:
#    api-docs:
#      path: /v3/api-docs
#    swagger-ui:
#      path: /swagger-ui.html
#  datasource:
#    name: HangHaePlusDataSource
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      maximum-pool-size: 3
#      connection-timeout: 10000
#      max-lifetime: 60000
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    open-in-view: false
#    generate-ddl: false
#    show-sql: false
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate.timezone.default_storage: NORMALIZE_UTC
#      hibernate.jdbc.time_zone: UTC

---
spring.config.activate.on-profile: local

spring:
  server:
    port: 8080
  jackson:
    time-zone: Asia/Seoul
  application:
    name: hhplus_concert[local]
  datasource:
    name: hhplus_concert
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    url: jdbc:mysql://localhost:3306/hhplus_concert?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: password1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # 스키마 변경 방지
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
logging:
  level:
    kr:
      hhplus: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha

---
spring.config.activate.on-profile: test
spring:
  server:
      port: 8080
  jackson:
    time-zone: Asia/Seoul
  application:
    name: hhplus_concert[test]
  datasource:
    name: hhplus_concert
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/test?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: password1!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha
