spring:
  profiles:
    active: local
  server:
    port: 8080
  jackson:
    time-zone: Asia/Seoul
  application:
    name: hhplus_concert[local]
  datasource:
    name: hhplus_concert
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    url: jdbc:mysql://localhost:3306/hhplus_concert?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: password1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # 스키마 변경 방지
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      hibernate:
        format_sql: true
  sql:
    init:
      schema-locations: classpath:/schema.sql
  data:
    redis:
      host: my-redis
      port: 6379
      timeout: 6000ms
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.orm.jpa: DEBUG
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: alpha
