spring:
  application:
    name: hhplus
  profiles:
    active: local
  springdoc:
    api-docs:
      path: /v3/api-docs  # OpenAPI 문서 기본 경로
    swagger-ui:
      path: /swagger-ui.html  # Swagger UI 기본 경로
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

---
spring.config.activate.on-profile: local
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hhplus?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

---
spring.config.activate.on-profile: test
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8:///graphy?TC_INITSCRIPT=file:src/test/resources/schema.sql
    username: root
    password: password1!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
